sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vishalcool401/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vishalcool1401/docker-react npm run test
